"""Export FIR coefficients as a Verilog/SystemVerilog snippet.

The Streamlit app (1.3) calls :func:`taps_to_verilog` and renders the result
in a read-only text field so the user can copy-paste it straight into the
FPGA project (1.4).
"""
from __future__ import annotations

from typing import Iterable

import numpy as np

from .filter_fixed import quantize_taps_q15


def _hex16(value: int) -> str:
    """Format a signed int16 value as a 16-bit two's-complement hex literal."""
    if value < 0:
        value = (1 << 16) + value
    return f"16'h{value & 0xFFFF:04X}"


def taps_to_verilog(
    taps: Iterable[float] | np.ndarray,
    *,
    name: str = "B_TAPS",
    style: str = "systemverilog",
    columns: int = 4,
    include_metadata: bool = True,
    fs: int | None = None,
    f_low: float | None = None,
    f_high: float | None = None,
) -> str:
    """Render coefficients as a Verilog ``localparam`` array literal.

    Parameters
    ----------
    taps:
        Float coefficients in ``[-1, 1]`` (will be quantized to Q1.15) or an
        ``int16`` array (used verbatim).
    name:
        Parameter name (default ``B_TAPS``).
    style:
        ``"systemverilog"`` produces ``logic signed [15:0] B_TAPS [0:N-1]``;
        ``"verilog"`` produces ``reg signed [15:0] B_TAPS [0:N-1]``.
    columns:
        Number of values per line in the array literal.
    include_metadata:
        Prepend a ``//`` comment block with filter metadata (length, fs, band).
    """
    arr = np.asarray(list(taps) if not isinstance(taps, np.ndarray) else taps)
    if arr.dtype.kind == "f":
        q = quantize_taps_q15(arr)
    else:
        q = arr.astype(np.int16)

    n = q.shape[0]
    header_lines: list[str] = []
    if include_metadata:
        header_lines.append(f"// FIR bandpass filter coefficients (Q1.15, {n} taps)")
        if fs is not None:
            header_lines.append(f"// Sample rate: {fs} Hz")
        if f_low is not None and f_high is not None:
            header_lines.append(f"// Passband:    {f_low:.0f} - {f_high:.0f} Hz")
        header_lines.append("// Generated by filter_anc.verilog_export.taps_to_verilog")
        header_lines.append("")

    if style == "systemverilog":
        type_decl = f"localparam logic signed [15:0] {name} [0:{n - 1}] = '{{"
    elif style == "verilog":
        type_decl = (
            f"localparam signed [15:0] {name} [0:{n - 1}] = "
            "'{  // requires SystemVerilog support\n"
            f"// Use $readmemh on a .hex file for plain Verilog (see below)\n{{"
        )
    else:
        raise ValueError("style must be 'systemverilog' or 'verilog'")

    rows: list[str] = []
    for i in range(0, n, columns):
        chunk = q[i : i + columns]
        formatted = ", ".join(_hex16(int(v)) for v in chunk)
        suffix = "," if i + columns < n else ""
        rows.append("    " + formatted + suffix)

    body = "\n".join(rows)
    closing = "};"

    return "\n".join(header_lines + [type_decl, body, closing])


def taps_to_hex_file(taps: Iterable[float] | np.ndarray) -> str:
    """Render coefficients as a flat ``.hex`` text suitable for ``$readmemh``.

    One ``int16`` value per line, two's-complement hex without the ``16'h``
    prefix.
    """
    arr = np.asarray(list(taps) if not isinstance(taps, np.ndarray) else taps)
    q = quantize_taps_q15(arr) if arr.dtype.kind == "f" else arr.astype(np.int16)
    lines = []
    for v in q:
        v_i = int(v)
        if v_i < 0:
            v_i = (1 << 16) + v_i
        lines.append(f"{v_i & 0xFFFF:04X}")
    return "\n".join(lines) + "\n"
